# Stage 1 
# Base imnage

FROM  python:3.10-slim AS laptop

# Working Directory 
WORKDIR /Desktop

COPY requirements.txt .

# Install Dependancy
RUN apt-get update
RUN pip install --no-cache-dir -r requirements.txt

# ---------- Stage 2: Final Stage -----------------

FROM python:3.10-slim

WORKDIR /Desktop

RUN pip install flask
RUN pip install --upgrade pip
COPY --from=laptop /Desktop/  ./
COPY . .

# Expose port
EXPOSE 5000

# Set environment variable for Flask
ENV FLASK_APP=main.py
ENV FLASK_RUN_HOST=0.0.0.0

# Run the application
CMD ["flask", "run"]


